version: '2'

services:
  bind-dns:
    image: sameersbn/bind:9.16.1-20200524
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - bind:/data
    networks:
      - blax-network
volumes:
  bind:
    driver: local  
networks:
  blax-network:
    external: true